version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fithub-network
    depends_on:
      - front-end
    restart: unless-stopped

  front-end:
    build:
      context: ./FrontEnd
    volumes:
      - ./FrontEnd/.env:/app/.env
    networks:
      - fithub-network
    depends_on:
      - back-end

  back-end:
    build:
      context: ./BackEnd
    ports:
      - "3333:3333"
    networks:
      - fithub-network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "20s", "npm", "run", "start:prod"]
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - fithub-network

networks:
  fithub-network:
    driver: bridge